"""Local comparison and allowlisted TTS demo; not a benchmark interface."""
import streamlit as st
from hifimobinet.comparison import audio_bytes,audio_catalog
from hifimobinet.registry import manifest,repository_root,runtime_status

st.set_page_config(page_title='HiFi-MobiNet',page_icon='🔊',layout='wide')
st.title('HiFi-MobiNet speech comparison')
st.caption('Historical listening examples and functional text-to-speech. This demo is not a benchmark.')
root=repository_root()
models=manifest(root)['models']
labels={m['id']:m['label'] for m in models}
comparison,tts=st.tabs(['Audio comparison','Text-to-speech'])

with comparison:
    st.subheader('Compare the same sentence')
    st.write('Historical audio is played without additional loudness normalization. Audio release rights are under review.')
    try:
        catalog=audio_catalog(root)
        choices=list(dict.fromkeys(s['utterance_id'] for s in catalog['samples']))
        st.caption(catalog['selection_rule'])
        if not choices:
            st.info('No comparison samples have been catalogued yet.')
        else:
            selected=st.selectbox('Sentence',choices,key='sentence')
            samples=[s for s in catalog['samples'] if s['utterance_id']==selected]
            st.write(samples[0]['text'])
            columns=st.columns(2)
            for i,sample in enumerate(samples):
                with columns[i%2]:
                    st.markdown(f"**{labels.get(sample['model_id'],sample['model_id'])}**")
                    st.caption('Historical audio · '+sample['source'])
                    try:
                        st.audio(audio_bytes(sample,root),format='audio/wav')
                    except (OSError,ValueError) as error:
                        st.info(str(error))
                    st.caption(sample['source_locator'])
    except (OSError,ValueError,KeyError) as error:
        st.error('Audio catalog could not be verified: '+str(error))

@st.cache_resource(max_entries=1,show_spinner='Loading the verified model…')
def load_voice(model_id,artifact_hash):
    from hifimobinet.inference import Voice
    return Voice(model_id)

with tts:
    st.subheader('Generate a short English sentence')
    selected_model=st.selectbox('Model',list(labels),format_func=labels.get,key='model')
    record=next(m for m in models if m['id']==selected_model)
    available,reason=runtime_status(record,root)
    if available: st.success(reason)
    else: st.info('Unavailable: '+reason)
    text=st.text_area('Text',value='The birch canoe slid on the smooth planks.',max_chars=300,height=100)
    st.caption('CPU FP32 only. Maximum 300 characters. No checkpoint upload or custom model path.')
    if st.button('Synthesize',disabled=not available,type='primary'):
        try:
            voice=load_voice(selected_model,record['artifact']['sha256'])
            with st.spinner('Generating audio…'):
                wav=voice.synthesize(text)
            st.audio(wav,format='audio/wav')
            st.download_button('Download generated WAV',wav,file_name=selected_model+'.wav',mime='audio/wav')
            st.caption('Newly generated by this installation; not a historical research sample. Peak-scaled PCM16 output.')
        except Exception as error:
            # End-user messages contain no traceback or model paths.
            st.error('Synthesis failed. Check input, model availability and local dependencies.')
            st.caption(type(error).__name__)
